# For more information: https://laravel.com/docs/sail
version: '3.7'
services:

    nuxt3:
        container_name: nuxt3
        image: node:16.17.0
        command: bash -c "yarn install --check-files && yarn generate"
        volumes:
            - ./nuxt3:/nuxt3
            - ./laravel/public:/nuxt3/.laravel-public
        working_dir: /nuxt3
        env_file: .env
        environment:
            - HOST=${NUXT_HOST:-0.0.0.0}
            - PORT=${NUXT_PORT:-3000}
    
    laravel:
        container_name: laravel
        image: sail-8.1/app
        entrypoint: bash -c "composer install && php artisan app:install && start-container"
        build:
            context: ./laravel/docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        env_file: .env
        ports:
            - '${APP_PORT:-443}:80'
            - '${VITE_PORT:-5173}:5173'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './laravel:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-app}'
            MYSQL_USER: '${DB_USERNAME:-root}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './laravel/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-root}"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local