<?php

return [
  'collate' => 'utf8mb4_unicode_ci',
  'engine' => 'InnoDB',
  'tables' => [
    'app_file' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'slug' => 'VARCHAR(255) NULL DEFAULT NULL',
        'name' => 'VARCHAR(255) NULL DEFAULT NULL',
        'description' => 'TEXT NULL DEFAULT NULL',
        'size' => 'INT(10) NULL DEFAULT NULL',
        'mime' => 'VARCHAR(100) NULL DEFAULT NULL',
        'ext' => 'VARCHAR(5) NULL DEFAULT NULL',
        'folder' => 'VARCHAR(255) NULL DEFAULT NULL',
        'content' => 'LONGBLOB NULL DEFAULT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [],
    ],
    'app_mail' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'name' => 'VARCHAR(255) NOT NULL',
        'email_to' => 'VARCHAR(255) NOT NULL',
        'subject' => 'VARCHAR(255) NOT NULL',
        'content' => 'TEXT NOT NULL',
        'send_attempt' => 'INT(10) NOT NULL',
        'send_group' => 'VARCHAR(255) NOT NULL',
        'sent' => 'INT(10) NOT NULL',
        'read' => 'INT(10) NOT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [],
    ],
    'app_mail_template' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'slug' => 'VARCHAR(255) NOT NULL',
        'name' => 'VARCHAR(255) NOT NULL',
        'subject' => 'VARCHAR(255) NOT NULL',
        'content' => 'TEXT NOT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [],
    ],
    'app_place' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'name' => 'VARCHAR(255) NULL DEFAULT NULL',
        'route' => 'VARCHAR(255) NULL DEFAULT NULL',
        'number' => 'VARCHAR(10) NULL DEFAULT NULL',
        'zipcode' => 'VARCHAR(10) NULL DEFAULT NULL',
        'complement' => 'VARCHAR(255) NULL DEFAULT NULL',
        'reference' => 'VARCHAR(255) NULL DEFAULT NULL',
        'district' => 'VARCHAR(255) NULL DEFAULT NULL',
        'city' => 'VARCHAR(255) NULL DEFAULT NULL',
        'state' => 'VARCHAR(255) NULL DEFAULT NULL',
        'state_short' => 'VARCHAR(5) NULL DEFAULT NULL',
        'country' => 'VARCHAR(255) NULL DEFAULT NULL',
        'country_short' => 'VARCHAR(5) NULL DEFAULT NULL',
        'lat' => 'DOUBLE NULL DEFAULT NULL',
        'lng' => 'DOUBLE NULL DEFAULT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [],
    ],
    'app_settings' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'name' => 'VARCHAR(255) NOT NULL',
        'value' => 'TEXT NULL DEFAULT NULL',
        'public' => 'INT(10) NOT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [],
    ],
    'app_user' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'name' => 'VARCHAR(255) NULL DEFAULT NULL',
        'email' => 'VARCHAR(255) NULL DEFAULT NULL',
        'email_verified_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'password' => 'VARCHAR(255) NULL DEFAULT NULL',
        'group_id' => 'BIGINT(20) UNSIGNED NULL DEFAULT NULL',
        'remember_token' => 'VARCHAR(100) NULL DEFAULT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [
        'group_id' => [
          'to_table' => 'app_user_group',
          'to_field' => 'id',
          'on_update' => 'NO ACTION',
          'on_delete' => 'NO ACTION',
        ],
      ],
    ],
    'app_user_group' => [
      'pk' => 'id',
      'auto_increment' => false,
      'fields' => [
        'id' => 'BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT',
        'slug' => 'VARCHAR(255) NULL DEFAULT NULL',
        'name' => 'VARCHAR(255) NULL DEFAULT NULL',
        'permissions' => 'TEXT NULL DEFAULT NULL',
        'created_at' => 'TIMESTAMP NULL DEFAULT NULL',
        'updated_at' => 'TIMESTAMP NULL DEFAULT NULL',
      ],
      'fks' => [],
    ],
  ],
];